# SPDX-FileCopyrightText: 2023 Thomas Breitner
#
# SPDX-License-Identifier: CC0-1.0

name: Publish github pages

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
    ghpages:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11
        - name: Deploy to github pages
          run: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install .
            mkdocs gh-deploy --force --clean --verbose
