# SPDX-FileCopyrightText: 2023 Thomas Breitner
#
# SPDX-License-Identifier: CC0-1.0

name: Run some tests and update github pages

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
  tests:
    name: Run some tests, checks, formatters
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .[dev]
      - name: Run pytest
        run: pytest
      - name: Test REUSE compliance
        run: reuse lint
      - name: Run ruff
        uses: chartboost/ruff-action@v1

  ghpages:
    if: github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    uses: ./.github/workflows/ghpages.yml
